{% set name = "DFO-LS" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/DFO-LS-{{ version }}.tar.gz
  sha256: a6f20b9af9319a320c78f4f056d001028cea12c823edf683f4cf251abe42b311

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.11
    - pandas >=0.17
    - python >={{ python_min }}
    - scipy >=0.18

test:
  imports:
    - dfols
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/numericalalgorithmsgroup/dfols/
  summary: A flexible derivative-free solver for (bound constrained) nonlinear least-squares minimization
  license: GPL-3.0-or-later
  # License file manually packaged. See: https://github.com/numericalalgorithmsgroup/dfols/pull/19
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Alexis-D
