{% set name = "DFO-LS" %}
{% set version = "1.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 5b097e5e89a52f17d93209fcf8c73e38d091681f4940bbc615aa0b47ce687808

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.11
    - pandas >=0.17
    - python >=3.6
    - scipy >=0.18

test:
  imports:
    - dfols
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/numericalalgorithmsgroup/dfols/
  summary: A flexible derivative-free solver for (bound constrained) nonlinear least-squares minimization
  license: GPL-3.0-or-later
  # License file manually packaged. See: https://github.com/numericalalgorithmsgroup/dfols/pull/19
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Alexis-D
